# Generated by Django 4.2.7 on 2024-01-10 10:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='heartrate',
            field=models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AlterField(
            model_name='office',
            name='open',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1998), django.core.validators.MaxValueValidator(2022)]),
        ),
    ]
